### ISSUE TITLE
Why the ground truth file in data folder is different?

### ISSUE THREAD

**Issue by RemyYang** [lhanaf/MILD#2]
I run into an odd situation that two different ground truth files of NewCollege dataset appears. Here are the visualization of the two files:
one from MILD source code
![confusion_matrix](https://user-images.githubusercontent.com/9446867/31987658-13695abe-b99f-11e7-968b-770cd2eb1239.png)
and the other from http://www.robots.ox.ac.uk/~mobile/IJRR_2008_Dataset/data.html
![groundtruth](https://user-images.githubusercontent.com/9446867/31987751-5d222c1c-b99f-11e7-929c-24664ee6ac4f.png)
could anyone help out of this odd situation? Thank you very much!

**Comment by lhanaf** [comment]
Since in mild we attached the two images from two view angles of NewCollege dataset into a single image, and evaluate loop closures from the observations of two different view angles of the moving car, so we use the first groundtruth file. The later groundtruth file is used for methods that only using one view angles.

**Comment by RemyYang** [comment]
Would you please explain more on how to generate the first ground truth file? Looking forward to your reply!

**Comment by lhanaf** [comment]
I got the frist ground truth file from RTABMAP: http://introlab.github.io/rtabmap/

**Comment by dianqiliuze** [comment]
> I got the frist ground truth file from RTABMAP: http://introlab.github.io/rtabmap/

您好，很抱歉打扰您，我在上述地址中找到了ground truth的图片文件，并没有找到mat文件，请问可以提供一下地址链接吗？十分感谢
